[build]
  command = "npm run build"
  publish = "dist/la-street/browser"

[[redirects]]
  from = "/api/*"
  to = "https://dryapi.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
